import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ThemeProvider} from "./ThemeProvier"
import {ThemeSwitcher} from "@/app/ThemeSwitch";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body
        className={`${inter.className} bg-slate-50 dark:bg-[#0d1117]`}
    >
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <ThemeSwitcher/>
        <main>{children}</main>
    </ThemeProvider>
    </body>
    </html>
  )
}
